language: python
python:
  - "3.6"
install:
  - pip install -r requirements.txt
script:
  - tox
env:
  - TOXENV=py36
  - TOXENV=py27
addons:
  apt:
    packages:
    - libgstreamer0.10-dev
    - python-gst0.10-dev
